version: '3.8'

services:
  app:
    image: nestezup/scenario-manager:latest
    container_name: scenario-manager
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    # 필요한 경우 볼륨 추가
    # volumes:
    #   - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3" 